"""userid passing on  fix for goal model.

Revision ID: 05dea112daa7
Revises: e3b9cbc588ee
Create Date: 2025-07-18 13:53:13.080785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05dea112daa7'
down_revision: Union[str, Sequence[str], None] = 'e3b9cbc588ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
