"""fixed occurrence order naming issue.

Revision ID: 63042b8f4c6d
Revises: 05dea112daa7
Create Date: 2025-07-18 14:14:11.487920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63042b8f4c6d'
down_revision: Union[str, Sequence[str], None] = '05dea112daa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_occurrences', sa.Column('occurrence_order', sa.Integer(), nullable=False))
    op.drop_column('goal_occurrences', 'sequence_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_occurrences', sa.Column('sequence_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('goal_occurrences', 'occurrence_order')
    # ### end Alembic commands ###
