"""goaloccurrence_plan single parnet fixt.

Revision ID: 660e768f16c3
Revises: eed6c42501ae
Create Date: 2025-07-18 12:29:28.478054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660e768f16c3'
down_revision: Union[str, Sequence[str], None] = 'eed6c42501ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
