"""Add refinement_round and refined_from_plan_id to plansd

Revision ID: 804aca371c00
Revises: f85b3d301a15
Create Date: 2025-07-20 10:24:12.260097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804aca371c00'
down_revision: Union[str, Sequence[str], None] = 'f85b3d301a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('refinement_round', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('refined_from_plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plans', 'plans', ['refined_from_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.drop_column('plans', 'refined_from_plan_id')
    op.drop_column('plans', 'refinement_round')
    # ### end Alembic commands ###
