"""Single parent True in Plan model.

Revision ID: 804d0ea139fd
Revises: c93d4d4cd090
Create Date: 2025-07-17 19:52:04.362056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804d0ea139fd'
down_revision: Union[str, Sequence[str], None] = 'c93d4d4cd090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
