"""Add plan_id FKs to habit_cycles, goal_occurrences, tasks

Revision ID: 953d7256c376
Revises: 688ee7796cfc
Create Date: 2025-07-17 19:17:57.012955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953d7256c376'
down_revision: Union[str, Sequence[str], None] = '688ee7796cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_occurrences', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'goal_occurrences', 'plans', ['plan_id'], ['id'])
    op.add_column('habit_cycles', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'habit_cycles', 'plans', ['plan_id'], ['id'])
    op.add_column('tasks', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'plan_id')
    op.drop_constraint(None, 'habit_cycles', type_='foreignkey')
    op.drop_column('habit_cycles', 'plan_id')
    op.drop_constraint(None, 'goal_occurrences', type_='foreignkey')
    op.drop_column('goal_occurrences', 'plan_id')
    # ### end Alembic commands ###
