"""Scattered updates to various models.

Revision ID: c93d4d4cd090
Revises: 953d7256c376
Create Date: 2025-07-17 19:42:39.662876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93d4d4cd090'
down_revision: Union[str, Sequence[str], None] = '953d7256c376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('habit_cycles_habit_id_fkey'), 'habit_cycles', type_='foreignkey')
    op.create_foreign_key(None, 'habit_cycles', 'habit_goals', ['habit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habit_cycles', type_='foreignkey')
    op.create_foreign_key(op.f('habit_cycles_habit_id_fkey'), 'habit_cycles', 'goals', ['habit_id'], ['id'])
    # ### end Alembic commands ###
