"""Habitcycle_plan relationship fix on deletion.

Revision ID: cd98c738ce47
Revises: 804d0ea139fd
Create Date: 2025-07-18 11:13:35.808885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd98c738ce47'
down_revision: Union[str, Sequence[str], None] = '804d0ea139fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
