"""Rename Refined from to Source id + added the reverse relationship refined_plans in Plan model.

Revision ID: d477e45f5ba2
Revises: 804aca371c00
Create Date: 2025-07-30 15:05:23.622740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd477e45f5ba2'
down_revision: Union[str, Sequence[str], None] = '804aca371c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('source_plan_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('plans_refined_from_plan_id_fkey'), 'plans', type_='foreignkey')
    op.create_foreign_key(None, 'plans', 'plans', ['source_plan_id'], ['id'])
    op.drop_column('plans', 'refined_from_plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('refined_from_plan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.create_foreign_key(op.f('plans_refined_from_plan_id_fkey'), 'plans', 'plans', ['refined_from_plan_id'], ['id'])
    op.drop_column('plans', 'source_plan_id')
    # ### end Alembic commands ###
