"""multiple relationship fixes..

Revision ID: eed6c42501ae
Revises: f60805ffff25
Create Date: 2025-07-18 12:24:21.086443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed6c42501ae'
down_revision: Union[str, Sequence[str], None] = 'f60805ffff25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'feedback', ['plan_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='unique')
    # ### end Alembic commands ###
