"""Add goal_id FK to Feedback model.

Revision ID: f85b3d301a15
Revises: 507969308c7f
Create Date: 2025-07-18 21:18:26.205304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85b3d301a15'
down_revision: Union[str, Sequence[str], None] = '507969308c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('goal_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'feedback', 'goals', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'goal_id')
    # ### end Alembic commands ###
